export const SET_MENU = 'SET_MENU';
export const SET_USERS = 'SET_USERS';
export const FETCHING_TOGGLE = 'FETCHING_TOGGLE';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_FOLLOWING_USER = 'SET_FOLLOWING_USER';
export const SET_UNFOLLOWING_USER = 'SET_UNFOLLOWING_USER';
