export const SET_MENU = 'SET_MENU';
export const SET_USERS = 'SET_USERS';
export const FETCHING_TOGGLE = 'FETCHING_TOGGLE';
export const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_FOLLOWING_USER = 'SET_FOLLOWING_USER';
export const SET_UNFOLLOWING_USER = 'SET_UNFOLLOWING_USER';

export const SET_PROFILE = 'SET_PROFILE';

export const SET_MY_AUTH_DATA = 'SET_MY_AUTH_DATA';
export const SET_AUTH_ID = 'SET_AUTH_ID';
export const SET_USER_DATA = 'SET_USER_DATA';
